# Generated by Django 5.2.4 on 2025-08-03 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('frequency', models.CharField(max_length=10)),
                ('order', models.PositiveIntegerField(help_text='Position in display order')),
                ('category', models.CharField(choices=[('solat', 'Solat'), ('tilawah', 'Tilawah'), ('swot', 'SWOT')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_good_habit', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_todos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
