# Generated by Django 5.2.4 on 2025-08-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('path', models.CharField(help_text='Frontend route path (e.g., /dashboard)', max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Lucide-react or Shadcn UI icon name.', max_length=100)),
                ('role', models.CharField(choices=[('student', 'Student'), ('sitting_head', 'Sitting Head'), ('overall_head', 'Overall Head'), ('admin', 'Admin')], help_text='Role that can access this menu item.', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display; lower numbers appear first.')),
                ('visible', models.BooleanField(default=True, help_text='Whether this menu item should be shown.')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order'],
            },
        ),
    ]
