# Generated by Django 5.2.4 on 2025-08-03 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=10)),
                ('max_members', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('sitting_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headed_sittings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sittings.sitting')),
            ],
        ),
        migrations.CreateModel(
            name='SittingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('summary', models.TextField()),
                ('score', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sittings.sitting')),
            ],
        ),
        migrations.CreateModel(
            name='SittingMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sittings.sitting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'sitting')},
            },
        ),
    ]
